package landlordApp.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import landlordApp.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.21 18:48:28 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class AsukasTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi53 */
  @Test
  public void testRekisteroi53() {    // Asukas: 53
    Asukas asukas = new Asukas(1); 
    assertEquals("From: Asukas line: 55", 0, asukas.getId()); 
    asukas.rekisteroi(); 
    Asukas asukas2 = new Asukas(); 
    asukas2.rekisteroi(); 
    int n1 = asukas.getId(); 
    int n2 = asukas2.getId(); 
    assertEquals("From: Asukas line: 61", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse174 */
  @Test
  public void testParse174() {    // Asukas: 174
    Asukas kallu = new Asukas(); 
    kallu.parse("1 | 2 | Kallu | Kallunen | 0400841251 | kallu.kallunen@gmail.com | 20"); 
    assertEquals("From: Asukas line: 177", 1, kallu.getId()); 
    kallu.toString().equals("1|2|Kallu|Kallunen|0400841251|kallu.kallunen@gmail.com|20"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta306 */
  @Test
  public void testAseta306() {    // Asukas: 306
    Asukas asukas = new Asukas(); 
    assertEquals("From: Asukas line: 308", null, asukas.aseta(2,"Ankka Aku")); 
    assertEquals("From: Asukas line: 309", null, asukas.aseta(5,"eelis.koivusaari@gmail.com")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone350 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone350() throws CloneNotSupportedException {    // Asukas: 350
    Asukas asukas = new Asukas(); 
    asukas.parse("1 | 2 | Kallu | Kallunen | 0400841251 | kallu.kallunen@gmail.com | 20"); 
    Asukas kopio = asukas.clone(); 
    assertEquals("From: Asukas line: 355", asukas.toString(), kopio.toString()); 
    asukas.parse("1 | 2 | Ballu | Dallunen | 0400841251 | Ballu.Dallunen@gmail.com | 250"); 
    assertEquals("From: Asukas line: 357", false, kopio.toString().equals(asukas.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testEquals372 */
  @Test
  public void testEquals372() {    // Asukas: 372
    Asukas jasen1 = new Asukas(); 
    jasen1.parse("1 | 2 | Kallu | Kallunen | 0400841251 | kallu.kallunen@gmail.com | 20"); 
    Asukas jasen2 = new Asukas(); 
    jasen2.parse("1 | 2 | Kallu | Kallunen | 0400841251 | kallu.kallunen@gmail.com | 20"); 
    Asukas jasen3 = new Asukas(); 
    jasen3.parse("1 | 2 | Ballu | Kallunen | 0400841251 | kallu.kallunen@gmail.com | 20"); 
    assertEquals("From: Asukas line: 380", true, jasen1.equals(jasen2)); 
    assertEquals("From: Asukas line: 381", true, jasen2.equals(jasen1)); 
    assertEquals("From: Asukas line: 382", false, jasen1.equals(jasen3)); 
    assertEquals("From: Asukas line: 383", false, jasen3.equals(jasen2)); 
  } // Generated by ComTest END
}