package landlordApp.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import landlordApp.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2020.04.24 14:16:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TaloTest {



  // Generated by ComTest BEGIN
  /** testRekisteroi57 */
  @Test
  public void testRekisteroi57() {    // Talo: 57
    Talo talo = new Talo(); 
    assertEquals("From: Talo line: 59", 0, talo.getId()); 
    talo.rekisteroi(); 
    Talo talo2 = new Talo(); 
    talo2.rekisteroi(); 
    int n1 = talo.getId(); 
    int n2 = talo2.getId(); 
    assertEquals("From: Talo line: 65", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse128 */
  @Test
  public void testParse128() {    // Talo: 128
    Talo ta = new Talo(); 
    ta.parse("2|Taitoniekantie 9b|Jyväskylä|40773|1975"); 
    assertEquals("From: Talo line: 131", 2, ta.getId()); 
    ta.toString().equals("2|Taitoniekantie 9b|Jyväskylä|40773|1975"); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta237 */
  @Test
  public void testAseta237() {    // Talo: 237
    Talo uusi = new Talo(); 
    assertEquals("From: Talo line: 239", null, uusi.aseta(1,"Taitoniekantie 9")); 
    assertEquals("From: Talo line: 240", false, uusi.aseta(4, "abcd") == null); 
  } // Generated by ComTest END
}